const COPA_2026_MATCHES = [
  {
    "data": "11/06/2026",
    "hora": "16:00",
    "fase": "Grupo A",
    "partida": "México x África do Sul",
    "time_casa": "México",
    "time_fora": "África do Sul",
    "local": "Cidade do México (Estádio Azteca)",
    "eliminatoria": false,
    "gols_casa": 2,
    "gols_fora": 0,
    "id": 1
  },
  {
    "data": "11/06/2026",
    "hora": "23:00",
    "fase": "Grupo A",
    "partida": "Coreia do Sul x República Tcheca",
    "time_casa": "Coreia do Sul",
    "time_fora": "República Tcheca",
    "local": "Guadalajara (Estádio Akron)",
    "eliminatoria": false,
    "gols_casa": 2,
    "gols_fora": 1,
    "id": 2
  },
  {
    "data": "12/06/2026",
    "hora": "16:00",
    "fase": "Grupo B",
    "partida": "Canadá x Bósnia e Herzegovina",
    "time_casa": "Canadá",
    "time_fora": "Bósnia e Herzegovina",
    "local": "Toronto (BMO Field)",
    "eliminatoria": false,
    "gols_casa": 1,
    "gols_fora": 1,
    "id": 3
  },
  {
    "data": "12/06/2026",
    "hora": "22:00",
    "fase": "Grupo D",
    "partida": "Estados Unidos x Paraguai",
    "time_casa": "Estados Unidos",
    "time_fora": "Paraguai",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": false,
    "gols_casa": 4,
    "gols_fora": 1,
    "id": 4
  },
  {
    "data": "13/06/2026",
    "hora": "16:00",
    "fase": "Grupo B",
    "partida": "Catar x Suíça",
    "time_casa": "Catar",
    "time_fora": "Suíça",
    "local": "San Francisco (Levi's Stadium)",
    "eliminatoria": false,
    "id": 5,
    "gols_casa": 1,
    "gols_fora": 1
  },
  {
    "data": "13/06/2026",
    "hora": "19:00",
    "fase": "Grupo C",
    "partida": "Brasil x Marrocos",
    "time_casa": "Brasil",
    "time_fora": "Marrocos",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": false,
    "id": 6,
    "gols_casa": 1,
    "gols_fora": 1
  },
  {
    "data": "13/06/2026",
    "hora": "22:00",
    "fase": "Grupo C",
    "partida": "Haiti x Escócia",
    "time_casa": "Haiti",
    "time_fora": "Escócia",
    "local": "Boston (Gillette Stadium)",
    "eliminatoria": false,
    "id": 7,
    "gols_casa": 0,
    "gols_fora": 1
  },
  {
    "data": "14/06/2026",
    "hora": "01:00",
    "fase": "Grupo D",
    "partida": "Austrália x Turquia",
    "time_casa": "Austrália",
    "time_fora": "Turquia",
    "local": "Vancouver (BC Place)",
    "eliminatoria": false,
    "id": 8,
    "gols_casa": 2,
    "gols_fora": 0
  },
  {
    "data": "14/06/2026",
    "hora": "14:00",
    "fase": "Grupo E",
    "partida": "Alemanha x Curaçao",
    "time_casa": "Alemanha",
    "time_fora": "Curaçao",
    "local": "Houston (NRG Stadium)",
    "eliminatoria": false,
    "id": 9,
    "gols_casa": 7,
    "gols_fora": 1
  },
  {
    "data": "14/06/2026",
    "hora": "17:00",
    "fase": "Grupo F",
    "partida": "Holanda x Japão",
    "time_casa": "Holanda",
    "time_fora": "Japão",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": false,
    "id": 10,
    "gols_casa": 2,
    "gols_fora": 2
  },
  {
    "data": "14/06/2026",
    "hora": "20:00",
    "fase": "Grupo E",
    "partida": "Costa do Marfim x Equador",
    "time_casa": "Costa do Marfim",
    "time_fora": "Equador",
    "local": "Filadélfia (Lincoln Financial Field)",
    "eliminatoria": false,
    "id": 11,
    "gols_casa": 0,
    "gols_fora": 0,
    "tempo_jogo": "65'",
    "tempo_atualizado": 1781483448278
  },
  {
    "data": "14/06/2026",
    "hora": "23:00",
    "fase": "Grupo F",
    "partida": "Suécia x Tunísia",
    "time_casa": "Suécia",
    "time_fora": "Tunísia",
    "local": "Monterrey (Estádio BBVA)",
    "eliminatoria": false,
    "id": 12
  },
  {
    "data": "15/06/2026",
    "hora": "13:00",
    "fase": "Grupo H",
    "partida": "Espanha x Cabo Verde",
    "time_casa": "Espanha",
    "time_fora": "Cabo Verde",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": false,
    "id": 13
  },
  {
    "data": "15/06/2026",
    "hora": "16:00",
    "fase": "Grupo G",
    "partida": "Bélgica x Egito",
    "time_casa": "Bélgica",
    "time_fora": "Egito",
    "local": "Seattle (Lumen Field)",
    "eliminatoria": false,
    "id": 14
  },
  {
    "data": "15/06/2026",
    "hora": "19:00",
    "fase": "Grupo H",
    "partida": "Arábia Saudita x Uruguai",
    "time_casa": "Arábia Saudita",
    "time_fora": "Uruguai",
    "local": "Miami (Hard Rock Stadium)",
    "eliminatoria": false,
    "id": 15
  },
  {
    "data": "15/06/2026",
    "hora": "22:00",
    "fase": "Grupo G",
    "partida": "Irã x Nova Zelândia",
    "time_casa": "Irã",
    "time_fora": "Nova Zelândia",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": false,
    "id": 16
  },
  {
    "data": "16/06/2026",
    "hora": "16:00",
    "fase": "Grupo I",
    "partida": "França x Senegal",
    "time_casa": "França",
    "time_fora": "Senegal",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": false,
    "id": 17
  },
  {
    "data": "16/06/2026",
    "hora": "19:00",
    "fase": "Grupo I",
    "partida": "Iraque x Noruega",
    "time_casa": "Iraque",
    "time_fora": "Noruega",
    "local": "Boston (Gillette Stadium)",
    "eliminatoria": false,
    "id": 18
  },
  {
    "data": "16/06/2026",
    "hora": "22:00",
    "fase": "Grupo J",
    "partida": "Argentina x Argélia",
    "time_casa": "Argentina",
    "time_fora": "Argélia",
    "local": "Kansas City (Arrowhead Stadium)",
    "eliminatoria": false,
    "id": 19
  },
  {
    "data": "17/06/2026",
    "hora": "01:00",
    "fase": "Grupo J",
    "partida": "Áustria x Jordânia",
    "time_casa": "Áustria",
    "time_fora": "Jordânia",
    "local": "San Francisco (Levi's Stadium)",
    "eliminatoria": false,
    "id": 20
  },
  {
    "data": "17/06/2026",
    "hora": "14:00",
    "fase": "Grupo K",
    "partida": "Portugal x RD Congo",
    "time_casa": "Portugal",
    "time_fora": "RD Congo",
    "local": "Houston (NRG Stadium)",
    "eliminatoria": false,
    "id": 21
  },
  {
    "data": "17/06/2026",
    "hora": "17:00",
    "fase": "Grupo L",
    "partida": "Inglaterra x Croácia",
    "time_casa": "Inglaterra",
    "time_fora": "Croácia",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": false,
    "id": 22
  },
  {
    "data": "17/06/2026",
    "hora": "20:00",
    "fase": "Grupo L",
    "partida": "Gana x Panamá",
    "time_casa": "Gana",
    "time_fora": "Panamá",
    "local": "Toronto (BMO Field)",
    "eliminatoria": false,
    "id": 23
  },
  {
    "data": "17/06/2026",
    "hora": "23:00",
    "fase": "Grupo K",
    "partida": "Uzbequistão x Colômbia",
    "time_casa": "Uzbequistão",
    "time_fora": "Colômbia",
    "local": "Cidade do México (Estádio Azteca)",
    "eliminatoria": false,
    "id": 24
  },
  {
    "data": "18/06/2026",
    "hora": "13:00",
    "fase": "Grupo A",
    "partida": "República Tcheca x África do Sul",
    "time_casa": "República Tcheca",
    "time_fora": "África do Sul",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": false,
    "id": 25
  },
  {
    "data": "18/06/2026",
    "hora": "16:00",
    "fase": "Grupo B",
    "partida": "Suíça x Bósnia e Herzegovina",
    "time_casa": "Suíça",
    "time_fora": "Bósnia e Herzegovina",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": false,
    "id": 26
  },
  {
    "data": "18/06/2026",
    "hora": "19:00",
    "fase": "Grupo B",
    "partida": "Canadá x Catar",
    "time_casa": "Canadá",
    "time_fora": "Catar",
    "local": "Vancouver (BC Place)",
    "eliminatoria": false,
    "id": 27
  },
  {
    "data": "18/06/2026",
    "hora": "22:00",
    "fase": "Grupo A",
    "partida": "México x Coreia do Sul",
    "time_casa": "México",
    "time_fora": "Coreia do Sul",
    "local": "Guadalajara (Estádio Akron)",
    "eliminatoria": false,
    "id": 28
  },
  {
    "data": "19/06/2026",
    "hora": "16:00",
    "fase": "Grupo D",
    "partida": "Estados Unidos x Austrália",
    "time_casa": "Estados Unidos",
    "time_fora": "Austrália",
    "local": "Seattle (Lumen Field)",
    "eliminatoria": false,
    "id": 29
  },
  {
    "data": "19/06/2026",
    "hora": "19:00",
    "fase": "Grupo C",
    "partida": "Escócia x Marrocos",
    "time_casa": "Escócia",
    "time_fora": "Marrocos",
    "local": "Boston (Gillette Stadium)",
    "eliminatoria": false,
    "id": 30
  },
  {
    "data": "19/06/2026",
    "hora": "22:00",
    "fase": "Grupo C",
    "partida": "Brasil x Haiti",
    "time_casa": "Brasil",
    "time_fora": "Haiti",
    "local": "Filadélfia (Lincoln Financial Field)",
    "eliminatoria": false,
    "id": 31
  },
  {
    "data": "20/06/2026",
    "hora": "01:00",
    "fase": "Grupo D",
    "partida": "Turquia x Paraguai",
    "time_casa": "Turquia",
    "time_fora": "Paraguai",
    "local": "San Francisco (Levi's Stadium)",
    "eliminatoria": false,
    "id": 32
  },
  {
    "data": "20/06/2026",
    "hora": "14:00",
    "fase": "Grupo F",
    "partida": "Holanda x Suécia",
    "time_casa": "Holanda",
    "time_fora": "Suécia",
    "local": "Houston (NRG Stadium)",
    "eliminatoria": false,
    "id": 33
  },
  {
    "data": "20/06/2026",
    "hora": "17:00",
    "fase": "Grupo E",
    "partida": "Alemanha x Costa do Marfim",
    "time_casa": "Alemanha",
    "time_fora": "Costa do Marfim",
    "local": "Toronto (BMO Field)",
    "eliminatoria": false,
    "id": 34
  },
  {
    "data": "20/06/2026",
    "hora": "21:00",
    "fase": "Grupo E",
    "partida": "Equador x Curaçao",
    "time_casa": "Equador",
    "time_fora": "Curaçao",
    "local": "Kansas City (Arrowhead Stadium)",
    "eliminatoria": false,
    "id": 35
  },
  {
    "data": "21/06/2026",
    "hora": "01:00",
    "fase": "Grupo F",
    "partida": "Tunísia x Japão",
    "time_casa": "Tunísia",
    "time_fora": "Japão",
    "local": "Monterrey (Estádio BBVA)",
    "eliminatoria": false,
    "id": 36
  },
  {
    "data": "21/06/2026",
    "hora": "13:00",
    "fase": "Grupo H",
    "partida": "Espanha x Arábia Saudita",
    "time_casa": "Espanha",
    "time_fora": "Arábia Saudita",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": false,
    "id": 37
  },
  {
    "data": "21/06/2026",
    "hora": "16:00",
    "fase": "Grupo G",
    "partida": "Bélgica x Irã",
    "time_casa": "Bélgica",
    "time_fora": "Irã",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": false,
    "id": 38
  },
  {
    "data": "21/06/2026",
    "hora": "19:00",
    "fase": "Grupo H",
    "partida": "Uruguai x Cabo Verde",
    "time_casa": "Uruguai",
    "time_fora": "Cabo Verde",
    "local": "Miami (Hard Rock Stadium)",
    "eliminatoria": false,
    "id": 39
  },
  {
    "data": "21/06/2026",
    "hora": "22:00",
    "fase": "Grupo G",
    "partida": "Nova Zelândia x Egito",
    "time_casa": "Nova Zelândia",
    "time_fora": "Egito",
    "local": "Vancouver (BC Place)",
    "eliminatoria": false,
    "id": 40
  },
  {
    "data": "22/06/2026",
    "hora": "14:00",
    "fase": "Grupo J",
    "partida": "Argentina x Áustria",
    "time_casa": "Argentina",
    "time_fora": "Áustria",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": false,
    "id": 41
  },
  {
    "data": "22/06/2026",
    "hora": "18:00",
    "fase": "Grupo I",
    "partida": "França x Iraque",
    "time_casa": "França",
    "time_fora": "Iraque",
    "local": "Filadélfia (Lincoln Financial Field)",
    "eliminatoria": false,
    "id": 42
  },
  {
    "data": "22/06/2026",
    "hora": "21:00",
    "fase": "Grupo I",
    "partida": "Noruega x Senegal",
    "time_casa": "Noruega",
    "time_fora": "Senegal",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": false,
    "id": 43
  },
  {
    "data": "23/06/2026",
    "hora": "00:00",
    "fase": "Grupo J",
    "partida": "Jordânia x Argélia",
    "time_casa": "Jordânia",
    "time_fora": "Argélia",
    "local": "San Francisco (Levi's Stadium)",
    "eliminatoria": false,
    "id": 44
  },
  {
    "data": "23/06/2026",
    "hora": "14:00",
    "fase": "Grupo K",
    "partida": "Portugal x Uzbequistão",
    "time_casa": "Portugal",
    "time_fora": "Uzbequistão",
    "local": "Houston (NRG Stadium)",
    "eliminatoria": false,
    "id": 45
  },
  {
    "data": "23/06/2026",
    "hora": "17:00",
    "fase": "Grupo L",
    "partida": "Inglaterra x Gana",
    "time_casa": "Inglaterra",
    "time_fora": "Gana",
    "local": "Boston (Gillette Stadium)",
    "eliminatoria": false,
    "id": 46
  },
  {
    "data": "23/06/2026",
    "hora": "20:00",
    "fase": "Grupo L",
    "partida": "Panamá x Croácia",
    "time_casa": "Panamá",
    "time_fora": "Croácia",
    "local": "Toronto (BMO Field)",
    "eliminatoria": false,
    "id": 47
  },
  {
    "data": "23/06/2026",
    "hora": "23:00",
    "fase": "Grupo K",
    "partida": "Colômbia x RD Congo",
    "time_casa": "Colômbia",
    "time_fora": "RD Congo",
    "local": "Guadalajara (Estádio Akron)",
    "eliminatoria": false,
    "id": 48
  },
  {
    "data": "24/06/2026",
    "hora": "16:00",
    "fase": "Grupo B",
    "partida": "Bósnia e Herzegovina x Catar",
    "time_casa": "Bósnia e Herzegovina",
    "time_fora": "Catar",
    "local": "Seattle (Lumen Field)",
    "eliminatoria": false,
    "id": 49
  },
  {
    "data": "24/06/2026",
    "hora": "16:00",
    "fase": "Grupo B",
    "partida": "Suíça x Canadá",
    "time_casa": "Suíça",
    "time_fora": "Canadá",
    "local": "Vancouver (BC Place)",
    "eliminatoria": false,
    "id": 50
  },
  {
    "data": "24/06/2026",
    "hora": "19:00",
    "fase": "Grupo C",
    "partida": "Marrocos x Haiti",
    "time_casa": "Marrocos",
    "time_fora": "Haiti",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": false,
    "id": 51
  },
  {
    "data": "24/06/2026",
    "hora": "19:00",
    "fase": "Grupo C",
    "partida": "Escócia x Brasil",
    "time_casa": "Escócia",
    "time_fora": "Brasil",
    "local": "Miami (Hard Rock Stadium)",
    "eliminatoria": false,
    "id": 52
  },
  {
    "data": "24/06/2026",
    "hora": "22:00",
    "fase": "Grupo A",
    "partida": "República Tcheca x México",
    "time_casa": "República Tcheca",
    "time_fora": "México",
    "local": "Cidade do México (Estádio Azteca)",
    "eliminatoria": false,
    "id": 53
  },
  {
    "data": "24/06/2026",
    "hora": "22:00",
    "fase": "Grupo A",
    "partida": "África do Sul x Coreia do Sul",
    "time_casa": "África do Sul",
    "time_fora": "Coreia do Sul",
    "local": "Monterrey (Estádio BBVA)",
    "eliminatoria": false,
    "id": 54
  },
  {
    "data": "25/06/2026",
    "hora": "17:00",
    "fase": "Grupo E",
    "partida": "Curaçao x Costa do Marfim",
    "time_casa": "Curaçao",
    "time_fora": "Costa do Marfim",
    "local": "Filadélfia (Lincoln Financial Field)",
    "eliminatoria": false,
    "id": 55
  },
  {
    "data": "25/06/2026",
    "hora": "17:00",
    "fase": "Grupo E",
    "partida": "Equador x Alemanha",
    "time_casa": "Equador",
    "time_fora": "Alemanha",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": false,
    "id": 56
  },
  {
    "data": "25/06/2026",
    "hora": "20:00",
    "fase": "Grupo F",
    "partida": "Japão x Suécia",
    "time_casa": "Japão",
    "time_fora": "Suécia",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": false,
    "id": 57
  },
  {
    "data": "25/06/2026",
    "hora": "20:00",
    "fase": "Grupo F",
    "partida": "Tunísia x Holanda",
    "time_casa": "Tunísia",
    "time_fora": "Holanda",
    "local": "Kansas City (Arrowhead Stadium)",
    "eliminatoria": false,
    "id": 58
  },
  {
    "data": "25/06/2026",
    "hora": "23:00",
    "fase": "Grupo D",
    "partida": "Paraguai x Austrália",
    "time_casa": "Paraguai",
    "time_fora": "Austrália",
    "local": "San Francisco (Levi's Stadium)",
    "eliminatoria": false,
    "id": 59
  },
  {
    "data": "25/06/2026",
    "hora": "23:00",
    "fase": "Grupo D",
    "partida": "Turquia x Estados Unidos",
    "time_casa": "Turquia",
    "time_fora": "Estados Unidos",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": false,
    "id": 60
  },
  {
    "data": "26/06/2026",
    "hora": "16:00",
    "fase": "Grupo I",
    "partida": "Noruega x França",
    "time_casa": "Noruega",
    "time_fora": "França",
    "local": "Boston (Gillette Stadium)",
    "eliminatoria": false,
    "id": 61
  },
  {
    "data": "26/06/2026",
    "hora": "16:00",
    "fase": "Grupo I",
    "partida": "Senegal x Iraque",
    "time_casa": "Senegal",
    "time_fora": "Iraque",
    "local": "Toronto (BMO Field)",
    "eliminatoria": false,
    "id": 62
  },
  {
    "data": "26/06/2026",
    "hora": "21:00",
    "fase": "Grupo H",
    "partida": "Cabo Verde x Arábia Saudita",
    "time_casa": "Cabo Verde",
    "time_fora": "Arábia Saudita",
    "local": "Houston (NRG Stadium)",
    "eliminatoria": false,
    "id": 63
  },
  {
    "data": "26/06/2026",
    "hora": "21:00",
    "fase": "Grupo H",
    "partida": "Uruguai x Espanha",
    "time_casa": "Uruguai",
    "time_fora": "Espanha",
    "local": "Guadalajara (Estádio Akron)",
    "eliminatoria": false,
    "id": 64
  },
  {
    "data": "27/06/2026",
    "hora": "00:00",
    "fase": "Grupo G",
    "partida": "Egito x Irã",
    "time_casa": "Egito",
    "time_fora": "Irã",
    "local": "Seattle (Lumen Field)",
    "eliminatoria": false,
    "id": 65
  },
  {
    "data": "27/06/2026",
    "hora": "00:00",
    "fase": "Grupo G",
    "partida": "Nova Zelândia x Bélgica",
    "time_casa": "Nova Zelândia",
    "time_fora": "Bélgica",
    "local": "Vancouver (BC Place)",
    "eliminatoria": false,
    "id": 66
  },
  {
    "data": "27/06/2026",
    "hora": "18:00",
    "fase": "Grupo L",
    "partida": "Croácia x Gana",
    "time_casa": "Croácia",
    "time_fora": "Gana",
    "local": "Filadélfia (Lincoln Financial Field)",
    "eliminatoria": false,
    "id": 67
  },
  {
    "data": "27/06/2026",
    "hora": "18:00",
    "fase": "Grupo L",
    "partida": "Panamá x Inglaterra",
    "time_casa": "Panamá",
    "time_fora": "Inglaterra",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": false,
    "id": 68
  },
  {
    "data": "27/06/2026",
    "hora": "20:30",
    "fase": "Grupo K",
    "partida": "Colômbia x Portugal",
    "time_casa": "Colômbia",
    "time_fora": "Portugal",
    "local": "Miami (Hard Rock Stadium)",
    "eliminatoria": false,
    "id": 69
  },
  {
    "data": "27/06/2026",
    "hora": "20:30",
    "fase": "Grupo K",
    "partida": "RD Congo x Uzbequistão",
    "time_casa": "RD Congo",
    "time_fora": "Uzbequistão",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": false,
    "id": 70
  },
  {
    "data": "27/06/2026",
    "hora": "23:00",
    "fase": "Grupo J",
    "partida": "Argélia x Áustria",
    "time_casa": "Argélia",
    "time_fora": "Áustria",
    "local": "Kansas City (Arrowhead Stadium)",
    "eliminatoria": false,
    "id": 71
  },
  {
    "data": "27/06/2026",
    "hora": "23:00",
    "fase": "Grupo J",
    "partida": "Jordânia x Argentina",
    "time_casa": "Jordânia",
    "time_fora": "Argentina",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": false,
    "id": 72
  },
  {
    "id": 73,
    "data": "28/06/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "2º Grupo A x 2º Grupo B",
    "time_casa": "2º Grupo A",
    "time_fora": "2º Grupo B",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": true
  },
  {
    "id": 74,
    "data": "29/06/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo E x 3º Grupo A/B/C/D/F",
    "time_casa": "1º Grupo E",
    "time_fora": "3º Grupo A/B/C/D/F",
    "local": "Boston (Gillette Stadium)",
    "eliminatoria": true
  },
  {
    "id": 75,
    "data": "29/06/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo C x 2º Grupo F",
    "time_casa": "1º Grupo C",
    "time_fora": "2º Grupo F",
    "local": "Houston (NRG Stadium)",
    "eliminatoria": true
  },
  {
    "id": 76,
    "data": "29/06/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo I x 3º Grupo C/D/F/G/H",
    "time_casa": "1º Grupo I",
    "time_fora": "3º Grupo C/D/F/G/H",
    "local": "Monterrey (Estádio BBVA)",
    "eliminatoria": true
  },
  {
    "id": 77,
    "data": "30/06/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "2º Grupo E x 2º Grupo I",
    "time_casa": "2º Grupo E",
    "time_fora": "2º Grupo I",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": true
  },
  {
    "id": 78,
    "data": "30/06/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo A x 3º Grupo C/E/F/H/I",
    "time_casa": "1º Grupo A",
    "time_fora": "3º Grupo C/E/F/H/I",
    "local": "Cidade do México (Estádio Azteca)",
    "eliminatoria": true
  },
  {
    "id": 79,
    "data": "30/06/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo L x 3º Grupo E/H/I/J/K",
    "time_casa": "1º Grupo L",
    "time_fora": "3º Grupo E/H/I/J/K",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": true
  },
  {
    "id": 80,
    "data": "01/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo D x 3º Grupo B/E/F/I/J",
    "time_casa": "1º Grupo D",
    "time_fora": "3º Grupo B/E/F/I/J",
    "local": "San Francisco (Levi's Stadium)",
    "eliminatoria": true
  },
  {
    "id": 81,
    "data": "01/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo G x 3º Grupo A/E/H/I/J",
    "time_casa": "1º Grupo G",
    "time_fora": "3º Grupo A/E/H/I/J",
    "local": "Seattle (Lumen Field)",
    "eliminatoria": true
  },
  {
    "id": 82,
    "data": "01/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo F x 2º Grupo C",
    "time_casa": "1º Grupo F",
    "time_fora": "2º Grupo C",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": true
  },
  {
    "id": 83,
    "data": "02/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "2º Grupo D x 2º Grupo G",
    "time_casa": "2º Grupo D",
    "time_fora": "2º Grupo G",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": true
  },
  {
    "id": 84,
    "data": "02/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo B x 3º Grupo E/F/G/I/J",
    "time_casa": "1º Grupo B",
    "time_fora": "3º Grupo E/F/G/I/J",
    "local": "Vancouver (BC Place)",
    "eliminatoria": true
  },
  {
    "id": 85,
    "data": "02/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo H x 2º Grupo J",
    "time_casa": "1º Grupo H",
    "time_fora": "2º Grupo J",
    "local": "Miami (Hard Rock Stadium)",
    "eliminatoria": true
  },
  {
    "id": 86,
    "data": "03/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo J x 2º Grupo H",
    "time_casa": "1º Grupo J",
    "time_fora": "2º Grupo H",
    "local": "Kansas City (Arrowhead Stadium)",
    "eliminatoria": true
  },
  {
    "id": 87,
    "data": "03/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "1º Grupo K x 3º Grupo D/E/I/J/L",
    "time_casa": "1º Grupo K",
    "time_fora": "3º Grupo D/E/I/J/L",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": true
  },
  {
    "id": 88,
    "data": "03/07/2026",
    "hora": "A definir",
    "fase": "16-avos",
    "partida": "2º Grupo K x 2º Grupo L",
    "time_casa": "2º Grupo K",
    "time_fora": "2º Grupo L",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": true
  },
  {
    "id": 89,
    "data": "04/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 74 x Vencedor Jogo 77",
    "time_casa": "Vencedor Jogo 74",
    "time_fora": "Vencedor Jogo 77",
    "local": "Filadélfia (Lincoln Financial Field)",
    "eliminatoria": true
  },
  {
    "id": 90,
    "data": "04/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 73 x Vencedor Jogo 75",
    "time_casa": "Vencedor Jogo 73",
    "time_fora": "Vencedor Jogo 75",
    "local": "Houston (NRG Stadium)",
    "eliminatoria": true
  },
  {
    "id": 91,
    "data": "05/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 76 x Vencedor Jogo 78",
    "time_casa": "Vencedor Jogo 76",
    "time_fora": "Vencedor Jogo 78",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": true
  },
  {
    "id": 92,
    "data": "05/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 79 x Vencedor Jogo 80",
    "time_casa": "Vencedor Jogo 79",
    "time_fora": "Vencedor Jogo 80",
    "local": "Cidade do México (Estádio Azteca)",
    "eliminatoria": true
  },
  {
    "id": 93,
    "data": "06/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 83 x Vencedor Jogo 84",
    "time_casa": "Vencedor Jogo 83",
    "time_fora": "Vencedor Jogo 84",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": true
  },
  {
    "id": 94,
    "data": "06/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 81 x Vencedor Jogo 82",
    "time_casa": "Vencedor Jogo 81",
    "time_fora": "Vencedor Jogo 82",
    "local": "Seattle (Lumen Field)",
    "eliminatoria": true
  },
  {
    "id": 95,
    "data": "07/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 86 x Vencedor Jogo 88",
    "time_casa": "Vencedor Jogo 86",
    "time_fora": "Vencedor Jogo 88",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": true
  },
  {
    "id": 96,
    "data": "07/07/2026",
    "hora": "A definir",
    "fase": "Oitavas",
    "partida": "Vencedor Jogo 85 x Vencedor Jogo 87",
    "time_casa": "Vencedor Jogo 85",
    "time_fora": "Vencedor Jogo 87",
    "local": "Vancouver (BC Place)",
    "eliminatoria": true
  },
  {
    "id": 97,
    "data": "09/07/2026",
    "hora": "A definir",
    "fase": "Quartas",
    "partida": "Vencedor Jogo 89 x Vencedor Jogo 90",
    "time_casa": "Vencedor Jogo 89",
    "time_fora": "Vencedor Jogo 90",
    "local": "Boston (Gillette Stadium)",
    "eliminatoria": true
  },
  {
    "id": 98,
    "data": "10/07/2026",
    "hora": "A definir",
    "fase": "Quartas",
    "partida": "Vencedor Jogo 93 x Vencedor Jogo 94",
    "time_casa": "Vencedor Jogo 93",
    "time_fora": "Vencedor Jogo 94",
    "local": "Los Angeles (SoFi Stadium)",
    "eliminatoria": true
  },
  {
    "id": 99,
    "data": "11/07/2026",
    "hora": "A definir",
    "fase": "Quartas",
    "partida": "Vencedor Jogo 91 x Vencedor Jogo 92",
    "time_casa": "Vencedor Jogo 91",
    "time_fora": "Vencedor Jogo 92",
    "local": "Miami (Hard Rock Stadium)",
    "eliminatoria": true
  },
  {
    "id": 100,
    "data": "11/07/2026",
    "hora": "A definir",
    "fase": "Quartas",
    "partida": "Vencedor Jogo 95 x Vencedor Jogo 96",
    "time_casa": "Vencedor Jogo 95",
    "time_fora": "Vencedor Jogo 96",
    "local": "Kansas City (Arrowhead Stadium)",
    "eliminatoria": true
  },
  {
    "id": 101,
    "data": "14/07/2026",
    "hora": "A definir",
    "fase": "Semifinal",
    "partida": "Vencedor Jogo 97 x Vencedor Jogo 98",
    "time_casa": "Vencedor Jogo 97",
    "time_fora": "Vencedor Jogo 98",
    "local": "Dallas (AT&T Stadium)",
    "eliminatoria": true
  },
  {
    "id": 102,
    "data": "15/07/2026",
    "hora": "A definir",
    "fase": "Semifinal",
    "partida": "Vencedor Jogo 99 x Vencedor Jogo 100",
    "time_casa": "Vencedor Jogo 99",
    "time_fora": "Vencedor Jogo 100",
    "local": "Atlanta (Mercedes-Benz Stadium)",
    "eliminatoria": true
  },
  {
    "id": 103,
    "data": "18/07/2026",
    "hora": "A definir",
    "fase": "3º Lugar",
    "partida": "Perdedor Jogo 101 x Perdedor Jogo 102",
    "time_casa": "Perdedor Jogo 101",
    "time_fora": "Perdedor Jogo 102",
    "local": "Miami (Hard Rock Stadium)",
    "eliminatoria": true
  },
  {
    "id": 104,
    "data": "19/07/2026",
    "hora": "A definir",
    "fase": "Final",
    "partida": "Vencedor Jogo 101 x Vencedor Jogo 102",
    "time_casa": "Vencedor Jogo 101",
    "time_fora": "Vencedor Jogo 102",
    "local": "Nova York / Nova Jersey (MetLife)",
    "eliminatoria": true
  }
];
